---
# - name: Deploy cephadm
#   hosts: deployment_nodes
#   tasks:
#     - script: "{{ playbook_dir }}/../scripts/devices/install.sh"

#     - script: "{{ playbook_dir }}/../scripts/devices/deploy.sh"

# - name: Create pools
#   hosts: deployment_nodes[0]
#   tasks:
#     - script: "{{ playbook_dir }}/../scripts/devices/pools.sh"  